export const GET_HOME_LIST = 'home/GET_HOME_LIST';
export const HANDLE_HOME_LIST = 'home/HANDLE_HOME_LIST';
export const SET_MORE_CONTENT_LIST = 'home/SET_MORE_CONTENT_LIST';
export const CHANGE_SCROLL_TOP_SHOW = 'home/CHANGE_SCROLL_TOP_SHOW';
